c_january/11b_07_Valeri_Dobrev/config/routes.rb
Rails.application.routes.draw do
  root 'documents#list'
  
  devise_for :users
  
  resources :users
  resources :documents
    

  
 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

c_january/11b_07_Valeri_Dobrev/app/models/document.rb
class Document < ApplicationRecord
  mount_uploader :attachment, AttachmentUploader
  
   

end

c_january/11b_07_Valeri_Dobrev/app/models/user.rb
class User < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

c_january/11b_07_Valeri_Dobrev/app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
	before_action :authenticate_user!
	def list
    		@user = current_user.email
		@documents = Document.first(3)
  	end
	def index
		@documents = Document.all
	end
	def new
		@document = Document.new
	end
	def create
		@document= Document.new(document_params)
		if @document.save
			redirect_to "/documents"
		else
			render "new"
		end	
	end
	def show
		@document = Document.find(params[:id])
		@file_content = File.read("#{Rails.root}/public"+@document.attachment.to_s)
		
	end
	def destroy
	    document = Document.find(params[:id])
	    document.destroy
	    redirect_to documents_path
	end
	private
		def document_params
     			params.require(:document).permit(:name, :discription, :attachment)
   		end
		
	
end

c_january/11b_07_Valeri_Dobrev/app/views/documents/index.html.erb
<h1>All of your documents</h1>

<%= link_to 'New document', new_document_path %> <br/><br/>

<% @documents.each do |document| %>
         
	
            <%= link_to document.name, document_path(document) %> <br/>
	    <p><%= document.discription %></p>
            <h3><%= button_to "Delete",  document, method: :delete, confirm: "Are you sure that you wish to delete #{document.name}?" %></h3>
      	    
         
<% end %>

c_january/11b_07_Valeri_Dobrev/app/views/documents/list.html.erb
<h1>Welcome !</h1>
<p><%= @user %></p>

<%= link_to 'New document', new_document_path %> <br/><br/>
<% @documents.each do |document| %>
         
	
            <%= link_to document.name, document_path(document) %> <br/>
	    <p><%= document.discription %></p>
            <h3><%= button_to "Delete",  document, method: :delete, confirm: "Are you sure that you wish to delete #{document.name}?" %></h3>
      	    
         
<% end %>
<%= link_to "Logout", destroy_user_session_path, :method=>:delete %>

c_january/11b_07_Valeri_Dobrev/app/views/documents/new.html.erb
<%= form_for @document, html: { multipart: true } do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %></br>
      <%= f.label :discription %>
      <%= f.text_field :discription %></br>
      <%= f.label :attachment %>
      <%= f.file_field :attachment %></br>
      <%= f.submit "Create"%>
 <% end %>

c_january/11b_07_Valeri_Dobrev/app/views/documents/show.html.erb
<h1><%= @document.name %></h1>

<p>
   <strong>Discription: </strong> <%= @document.discription %><br />
  
</p>

<p><strong>File content:</strong> <%= @file_content %></p>

<hr />

<%= link_to 'Back', {:action => 'index'} %>

c_january/11b_07_Valeri_Dobrev/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Doc</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>