20190130-rails-homework/rails_homework_11a_18/config/routes.rb
Rails.application.routes.draw do
  
  root to: 'events#index'

  post "/organization/:id/add_person", to: "organizations#add_person", as: "add_person_to_organization" 
  post "/organization/:id/remove_person/:person_id", to: "organizations#remove_person", as: "remove_person_from_organization" 

  resources :organizations

  post "/attendance/create", to: "attendance#create", as: "create_attendance"
  post "/attendance/:id/destroy", to: "attendance#destroy", as: "destroy_attendance"
  # post "/organization/:id/destroy", to: "organization#destroy", as: "destroy_organization"

  resources :people
  resources :events
end

20190130-rails-homework/rails_homework_11a_18/app/models/person.rb
class Person < ApplicationRecord
    has_many :attendances
    has_many :events, through: :attendances
    
    belongs_to :organization, optional: true
    
    validates :name, presence: true

end

20190130-rails-homework/rails_homework_11a_18/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])
    @attendance = Attendance.new
    @attendance.person_id = @person.id
    session[:attendance] = @attendance
    @possible_attendances = Event.all - @person.events 
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end
  
  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :organization_id)
    end
end

20190130-rails-homework/rails_homework_11a_18/app/helpers/people_helper.rb
module PeopleHelper
end

20190130-rails-homework/rails_homework_11a_18/app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div class="alert">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <%= form.select :organization_id  do %>
    <%= options_from_collection_for_select(Organization.all, :id, :name  ) %>
  <% end %>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

20190130-rails-homework/rails_homework_11a_18/app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

20190130-rails-homework/rails_homework_11a_18/app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>
<%= link_to 'New Person', new_person_path %>
<br>


<% @people.each do |event|%>
    <div class="table_info">
      <p class="content">Name: <%= event.name %></p>
      <%= link_to "View", person_path(event)%>
    </div>
<% end %>

20190130-rails-homework/rails_homework_11a_18/app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

20190130-rails-homework/rails_homework_11a_18/app/views/people/show.html.erb
<h2>
  <strong class="name">Name:</strong>
  <%= @person.name %>
</h2>


<h3> Going to Events: </h3>
<% @person.events.each do |event| %>
  <p class = "field"> <strong class = "name"> -> </strong>  <%= event.name %>
    <% id = event.attendances.where(person_id: @person.id).take.id %>
    <%=link_to "Unregister", destroy_attendance_path(id), method: :destroy%> | 
    <%=link_to "View", event_path(event)%>
  </p>

<% end  %>  

<%= form_with model: @attendance, url: create_attendance_path, local: true do |f|  %>
    <%= f.select(:event_id) do%>
      <%=options_from_collection_for_select( @possible_attendances, :id, :name)%>
    <% end %>
  <%= f.submit "Register!" %>
<% end %>
 

<h3>  
  Organization: 
</h3>
  <% if @person.organization %> 
    <% name = @person.organization.name %>
  <% else %>
    <% name = "None"%>
  <% end %>

  <p><strong class = "name"> -> </strong><%= name %> </p> 


<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Delete', person_path(@person), method: :delete %> |
<%= link_to 'Back', people_path %>