c_january/11b_01_Alexandar_Karapenev/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'posts#index', as: 'home'

  resources :posts

end

c_january/11b_01_Alexandar_Karapenev/app/models/post.rb
class Post < ApplicationRecord
end

c_january/11b_01_Alexandar_Karapenev/app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def files

	end

end

c_january/11b_01_Alexandar_Karapenev/app/controllers/posts_controller.rb
class PostsController < ApplicationController

	http_basic_authenticate_with name: "root", password:"1234", except: [:index, :show]

	def index 
		@posts = Post.all 
	end	

	def new

	end	


	def edit
		@post = Post.find(params[:id]);
	end	

	def show
		@post = Post.find(params[:id]);
	end	

	def update
		@post = Post.find(params[:id]);
	
		@post.update(post_params)
		redirect_to @post
	end	

	def create

		@post = Post.new(post_params)

		@post.save
		redirect_to @post

	end	

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to post_params
	end	

	private def post_params
		params.require(:post).permit( :title, :body)
	end	


end

c_january/11b_01_Alexandar_Karapenev/app/helpers/posts_helper.rb
module PostsHelper
end

c_january/11b_01_Alexandar_Karapenev/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>



    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'%>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">Alex's Homework</a>
      </div>
      <ul class="nav navbar-nav">
        <li class="active"> <%= link_to "File Explorer", home_path %> </li> 
        <li> <%= link_to "Upload file", new_post_path %> </li>
      </ul>
     


    </div>
  </nav>




    </div>
  </header>




    <div class= "container">
      <%= yield %>

    </div>


  </body>
</html>